name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=20 --max-line-length=127 --statistics --exclude=inducer/__init__.py
    - name: Test with unittest
      run: |
        coverage run --omit=venv/*  -m unittest discover -s inducer/test
        coverage xml -o unit-testing.xml
    - name: Upload Unit-testing code coverage
      uses: codecov/codecov-action@v1
      with:
        flags: unittests # optional
        name: testing
        files: unit-testing.xml
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

